### ISSUE TITLE
max_elevs

### ISSUE THREAD

**Issue by youcanf** [NCAR/wrf_hydro_arcgis_preprocessor#17]
I am not sure if only my computer has this issue. But when running wrf_hydro_functions.py at line 2306:  "elevRange = {key:max_elevs[key]-val for key, val in min_elevs.items()}      # Get lake depths", I get an error reported as: NameError: global name 'max_elevs' is not defined. It doesn't make much sense to me, since I know it has been defined previously. But if I convert this line into a complete for loop, the error is gone and the program can resume. Here it is an example workaround that works for me: 

elevRange = {}
for key,val in min_elevs.items(): elevRange.update({key:max_elevs[key]-val})

**Comment by kmsampson** [comment]
This is interesting, as it should work the same way in a dictionary comprehension as it would with a complete for loop. Let me know if any of the recent updates have resolved the issue. I think this is related to your pull request #16.

**Comment by youcanf** [comment]
Thanks for your reply. I will try a recent version and let you know if I meet this issue again. It seems to me that it has something to do with my python. I will close this issue for now.
